### ISSUE TITLE
System.PlatformNotSupportedException: Could not load ffmpegaac or ffmpegaac.arm64.dll

### ISSUE THREAD

**Issue by pcolmer** [Mbucari/AAXClean.Codecs#6]
Can you please create an arm64 version of your library DLLs?

Unfortunately, for reasons that are beyond my understanding, applications like Libation hit this exception when trying to use AAXClean on a Windows on Arm system.

I cannot find a compatibility setting to get it working, hence my request for Arm64 support.

**Comment by Mbucari** [comment]
[Fixed](https://github.com/Mbucari/AAXClean.Codecs/commit/15ff7045b38b049eaf85c7a88fa347667805dba3).

**Comment by Mbucari** [comment]
@pcolmer Sorry, I think I misunderstood your issue and thought it was related to another problem.

Unfortunately, I am unable to compile native arm64 libs. I don't have an arm machine, so I'd have to cross-compile. Unfortunately again, the toolchain I use on windows doesn't support cross-compiling to windows arm. I've explored other toolchains with no success. This is just something I cannot do without access to a development machine running arm.

**Comment by Mbucari** [comment]
@pcolmer I don't know how tech-savvy you are, but if you're willing to help me by using your computer to compile the arm64 libraries for Windows, I may be able to get this done.

**Comment by pcolmer** [comment]
@Mbucari My immediate need has gone away as I've been hitting other issues with my Arm Surface so I'm reverting to my Intel Surface for the problematic software.

I don't know how you are currently building your libraries, but it might (should?) be possible to use Docker images in your GitHub workflows. CoPilot suggested the following build steps:

```
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.0'
    - name: Build for Intel
      run: dotnet publish -c Release --runtime linux-x64
    - name: Build for ARM
      run: dotnet publish -c Release --runtime linux-arm64
```
